const books = [
    {
      ISBN: 2,
      Name: "The House of Mirth",
      description: "A classic novel...",
      Image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1328729186i/17728.jpg",
      Category: "Classics",
      author: "Edith Wharton",
      price: 150,
      numberofpage: 40,
    },
    {
      ISBN: 3,
      Name: "The Sun Also Rises",
      description: "A novel of the Lost Generation...",
      Image: "https://upload.wikimedia.org/wikipedia/commons/8/8b/The_Sun_Also_Rises_%281st_ed._cover%29.jpg",
      Category: "Literature",
      author: "Ernest Hemingway",
      price: 200,
      numberofpage: 55,
    },
    {
      ISBN: 4,
      Name: "Vile Bodies",
      description: "Satirical novel on high society...",
      Image: "https://upload.wikimedia.org/wikipedia/en/5/50/Viles_Bodies.jpg",
      Category: "Satire",
      author: "Evelyn Waugh",
      price: 180,
      numberofpage: 48,
    },
    {
      ISBN: 5,
      Name: "A Scanner Darkly",
      description: "A dystopian science fiction novel...",
      Image: "https://upload.wikimedia.org/wikipedia/en/2/27/AScannerDarkly%281stEd%29.jpg",
      Category: "Sci-Fi",
      author: "Philip K. Dick",
      price: 300,
      numberofpage: 78,
    },
    {
      ISBN: 6,
      Name: "Moab Is My Washpot",
      description: "A memoir by Stephen Fry...",
      Image: "https://upload.wikimedia.org/wikipedia/en/a/a0/Stephen_Fry_moab_is_my_washpot.jpg",
      Category: "Memoir",
      author: "Stephen Fry",
      price: 350,
      numberofpage: 80,
    },
    {
      ISBN: 9,
      Name: "Brave New World",
      description: "A dystopian future society...",
      Image: "https://upload.wikimedia.org/wikipedia/en/6/62/BraveNewWorld_FirstEdition.jpg",
      Category: "Dystopian",
      author: "Aldous Huxley",
      price: 500,
      numberofpage: 110,
    },
    {
      ISBN: 10,
      Name: "Rosemary and Rue",
      description: "Urban fantasy novel...",
      Image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1406866868i/6294549.jpg",
      Category: "Fantasy",
      author: "Seanan McGuire",
      price: 550,
      numberofpage: 45,
    },
    {
      ISBN: 11,
      Name: "Pale Fire",
      description: "A metafictional novel...",
      Image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388155863i/7805.jpg",
      Category: "Literary Fiction",
      author: "Vladimir Nabokov",
      price: 600,
      numberofpage: 130,
    },
    {
      ISBN: 12,
      Name: "In Cold Blood",
      description: "True crime classic...",
      Image: "https://upload.wikimedia.org/wikipedia/en/e/ef/In_Cold_Blood-Truman_Capote.jpg",
      Category: "True Crime",
      author: "Truman Capote",
      price: 320,
      numberofpage: 100,
    },
    {
      ISBN: 13,
      Name: "Behold, Here's Poison",
      description: "A classic mystery...",
      Image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1320460133i/311135.jpg",
      Category: "Mystery",
      author: "Georgette Heyer",
      price: 240,
      numberofpage: 60,
    },
    {
      ISBN: 14,
      Name: "Band of Brothers",
      description: "WWII historical account...",
      Image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388247701i/42389.jpg",
      Category: "History",
      author: "Stephen E. Ambrose",
      price: 420,
      numberofpage: 75,
    },
    {
      ISBN: 15,
      Name: "The Dark Tower",
      description: "Epic fantasy conclusion...",
      Image: "https://upload.wikimedia.org/wikipedia/en/5/54/Thedarktower7.jpg",
      Category: "Fantasy",
      author: "Stephen King",
      price: 390,
      numberofpage: 300,
    }
  ];
  